variable avail_zone {}
variable env_prefix {}
variable instance_type {}
variable public_key_location {}
variable private_key_location {}
variable allowed_ip {}
variable net-subnet {}
variable vpc_id {}
variable image_name {}